apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-rate-limit
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
plugin: rate-limiting
config:
  second: 7
  hour: 10000
  limit_by: consumer
  policy: local