apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: functions
  labels:
    app: functions
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"