INSERT INTO menu_types VALUES('DRINK');
INSERT INTO menu_types VALUES('FOOD');
INSERT INTO menu_types VALUES('LUNCH');
INSERT INTO menu_types VALUES('SEASONAL');
INSERT INTO menu_types VALUES('TAKEOUT');
INSERT INTO menu_types VALUES('MORNING');
